idf_component_register(
    SRCS
        "thread_joiner.c"
        "thread_node.c"
        "thread_coap.c"
        "thread_discovery.c"
    INCLUDE_DIRS "include"
    REQUIRES
        esp_event
        esp_netif
        esp_timer
        openthread
        nvs_flash
        vfs
        freertos
        boot_btn
        status_led
        device
)
