idf_component_register(
    SRCS
        "core/thread_joiner.c"
        "core/thread_node.c"
        "core/thread_coap.c"
        "core/thread_discovery.c"
    INCLUDE_DIRS "core/include" "include"
    REQUIRES
        esp_event
        esp_netif
        esp_timer
        openthread
        nvs_flash
        vfs
        freertos
        boot_btn
        status_led
        device
)
